version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: graph_ql_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dice_platform_network

volumes:
  postgres_data:

networks:
  dice_platform_network:
    driver: bridge